=== DinoChiesa/devrel/references/mock-iam-v1/test/schemas/adminToken.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "access_token": {
      "type": "string",
      "minLength": 1
    },
    "expires_in": {
      "type": "number"
    },
    "refresh_expires_in": {
      "type": "number"
    },
    "refresh_token": {
      "type": "string",
      "minLength": 1
    },
    "token_type": {
      "type": "string",
      "minLength": 1
    },
    "not-before-policy": {
      "type": "number"
    },
    "session_state": {
      "type": "string",
      "minLength": 1
    },
    "scope": {
      "type": "string",
      "minLength": 1
    }
  },
  "required": [
    "access_token",
    "expires_in",
    "refresh_expires_in",
    "refresh_token",
    "token_type",
    "not-before-policy",
    "session_state",
    "scope"
  ]
}

=== DinoChiesa/devrel/references/mock-iam-v1/src/responses/authCodeToken.json
{
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuOGlYX0tZZDM0OXFvX01jYmhHbUtWU0ZPbDFMQzJremh3WUI2bzI1eVNNIn0.eyJleHAiOjE1OTM3NTk3MDIsImlhdCI6MTU5Mzc1OTY0MiwiYXV0aF90aW1lIjoxNTkzNzU4NDE1LCJqdGkiOiI1YmFlY2QwNy0xMWFhLTQ1Y2UtYjFmMS03ZTJlYjE1MWE4YTYiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjpbIm1hc3Rlci1yZWFsbSIsImFjY291bnQiXSwic3ViIjoiNWM5ZjNmYTctYmVmMS00MDVjLWIwNzUtYmMzNTQ0NDI3YWExIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2VhbnMtY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6IjkxMTRmY2ZjLWI3MDQtNGNkMS04OTFhLTU2MDcwODQ3NjZmNCIsImFjciI6IjAiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiY3JlYXRlLXJlYWxtIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsibWFzdGVyLXJlYWxtIjp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.JpNdL1_uqGhez7kPDNIx1V7S5ZXHpHnMF_7k8unw5_fzoAKwzXwc6Xt7kMgwt9VTwUYyNNGXN4dTLGsN9BeTm_il_NCZy7UNYtAmKM7CdneRA8PSGVNyQhrGyXmnPlC3oCa8QXNcRTAvXLfhYFCayBix3musie3wtUbuICSB6GLbGsriPdlsv6DrJUkLOPa9l-OV8_fVRcgVU9m1yj6Up4NU6owwFyvQx5B9f_RmiCQ_B0zeQBN5SRKBpKBUPLYztUgyk0lmbtGsiOaclqdfQzWY9ejxhTlbSHJpxsuzAl8AhijIji3SgLcpYBwSkAQL2i3n8m6FcjRteWLWQXFzVQ",
  "expires_in": 60,
  "refresh_expires_in": 1800,
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1YTZkNzIxYS04MzJjLTRiMGQtOTkwZC1lZmE2ZTFhMjdlODIifQ.eyJleHAiOjE1OTM3NjE0NDIsImlhdCI6MTU5Mzc1OTY0MiwianRpIjoiYmQ3ZTZjOGYtZTMzZS00N2VkLTk2YjItM2I1MTk2ZjQyZjE4IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI1YzlmM2ZhNy1iZWYxLTQwNWMtYjA3NS1iYzM1NDQ0MjdhYTEiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoic2VhbnMtY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6IjkxMTRmY2ZjLWI3MDQtNGNkMS04OTFhLTU2MDcwODQ3NjZmNCIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCJ9.MEPP-vIJrO4uDlQ0NH1dYaxuAPwhqx2lF8ypu25F5mA",
  "token_type": "bearer",
  "not-before-policy": 0,
  "session_state": "9114fcfc-b704-4cd1-891a-5607084766f4",
  "scope": "profile email"
}

=== DinoChiesa/devrel/references/mock-iam-v1/src/responses/passwordToken.json
{
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuOGlYX0tZZDM0OXFvX01jYmhHbUtWU0ZPbDFMQzJremh3WUI2bzI1eVNNIn0.eyJleHAiOjE1OTM3NTk1NTUsImlhdCI6MTU5Mzc1OTQ5NSwianRpIjoiNmI0M2NjM2YtMTdjYS00YjVjLWI5NzAtNmZjMmYwMWQ0MWI5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI2MGI1ZDc4Ny02NmJmLTQ0ODAtYjcyYi0yOTI1M2JjOWI3NzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzZWFucy1jbGllbnQiLCJzZXNzaW9uX3N0YXRlIjoiYzEyNjBjNGQtMDg1ZS00ZmFkLTkzYWItODUwNTMwYmZjZDQ2IiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzb21lb25lIn0.XD3hpludO7T7MU249G5lxLnO_JocPB_HRyJ9_Z3pvNWmhll2uvEOqx4wjqWHzDQ_MGZLWmziZ7MJDyvDoLXQKDy7mtF0b36Piz9MRldP-I7W_mG9W4gG83x-Yd2GqM9hPrBbfZ3E8f9tRr7LQKflO-y9z2XMMj8HVnfzjY5P2g13jBBiYZgLf7yM5vr9kmBZwX2YLfwjuQDWFGinQ0Rq0lIt8JBS5wifIQ_XiV61rOmqNXCJgZ3oUqMWu68kIpkOtZuKmQcHrtylATgEP_hrTk7GB2yjdk1ond19JLPU5A4899q1wHBtReFPnJsoMQn9EiZTFoueopJLSzRVN7e05w",
  "expires_in": 60,
  "refresh_expires_in": 1800,
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1YTZkNzIxYS04MzJjLTRiMGQtOTkwZC1lZmE2ZTFhMjdlODIifQ.eyJleHAiOjE1OTM3NjEyOTUsImlhdCI6MTU5Mzc1OTQ5NSwianRpIjoiZTEyYTk2N2UtZWRkMi00MzExLWFlODUtMmE4N2M5ZTJiOWU2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI2MGI1ZDc4Ny02NmJmLTQ0ODAtYjcyYi0yOTI1M2JjOWI3NzgiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoic2VhbnMtY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6ImMxMjYwYzRkLTA4NWUtNGZhZC05M2FiLTg1MDUzMGJmY2Q0NiIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCJ9.0XW6yQWCaIx8mAE4qK9iLHXk01_0nsMjGgWW2brtUL8",
  "token_type": "bearer",
  "not-before-policy": 0,
  "session_state": "c1260c4d-085e-4fad-93ab-850530bfcd46",
  "scope": "profile email"
}

=== DinoChiesa/devrel/references/mock-iam-v1/src/responses/adminToken.json
{
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuOGlYX0tZZDM0OXFvX01jYmhHbUtWU0ZPbDFMQzJremh3WUI2bzI1eVNNIn0.eyJleHAiOjE1OTM3NTg4MTcsImlhdCI6MTU5Mzc1ODc1NywianRpIjoiMGI5MmE5ZTUtMTZjZS00ZjA2LWEwYjctZGYyNWU3NTY3MWYzIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL21hc3RlciIsInN1YiI6IjVjOWYzZmE3LWJlZjEtNDA1Yy1iMDc1LWJjMzU0NDQyN2FhMSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiI4NmRjODM4YS1kOTZkLTQ1MWItODJjZS1iODIyMWMxMDY2Y2IiLCJhY3IiOiIxIiwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiJ9.Q5Q7vkuCgAU22A78TiRTNbB2lVlSf-yKBHNhAAtipfFssZ0NWmoR7YkMVWVHXD2zQK0caT0bXtkbRu7UHjnHpzOXUq60YEnngjbEKJDd485g9ngh4dYxGqlVdBrtRAEfn0HPM-BC9zfB_LmQEdH7D_BV0TMxR1Aef_IaegN0xtROs8YxIc4_eriKc14JG-4q79DlPDzgTG5KxSQhexlpIoJKj1ki908xt2HN4OjbIXEcIy1ACyKbhtEnA-mHhxDZ_gAoTxHZSx8B_mOWlMGm3M8H8yogNwBJH_rSTKXHubs6gD0U6aNkfKBYzm5IxFQ6rz7xmQDETrKPV191wscBuw",
  "expires_in": 60,
  "refresh_expires_in": 1800,
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1YTZkNzIxYS04MzJjLTRiMGQtOTkwZC1lZmE2ZTFhMjdlODIifQ.eyJleHAiOjE1OTM3NjA1NTcsImlhdCI6MTU5Mzc1ODc1NywianRpIjoiZDE0MTQ3NGEtMWFjNy00ZWEwLTgwNTAtODUwOTBiZDcyYTNjIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiI1YzlmM2ZhNy1iZWYxLTQwNWMtYjA3NS1iYzM1NDQ0MjdhYTEiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiYWRtaW4tY2xpIiwic2Vzc2lvbl9zdGF0ZSI6Ijg2ZGM4MzhhLWQ5NmQtNDUxYi04MmNlLWI4MjIxYzEwNjZjYiIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCJ9.co3xfxjjLShchUdabGf4TRLhsy0QdmEmbIGgO0NvZCc",
  "token_type": "bearer",
  "not-before-policy": 0,
  "session_state": "86dc838a-d96d-451b-82ce-b8221c1066cb",
  "scope": "profile email"
}

=== DinoChiesa/devrel/references/mock-iam-v1/src/responses/clientCredentialsToken.json
{
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuOGlYX0tZZDM0OXFvX01jYmhHbUtWU0ZPbDFMQzJremh3WUI2bzI1eVNNIn0.eyJleHAiOjE1OTM3NTkzMjQsImlhdCI6MTU5Mzc1OTI2NCwianRpIjoiZDAwMmJjYTEtODFjYy00MzBjLWE2ZDctNjUxZTZlMjEyNzNiIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJhYTBhZTc4OC1jYjEwLTQ0OTEtYTg2ZS1jOWJjZmUzOWRhMTQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzZWFucy1jbGllbnQiLCJzZXNzaW9uX3N0YXRlIjoiNWI1NjU4ZjUtZjI4Zi00MjQyLWI1NDYtYjljYzBjNzBkOGE2IiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsic2VhbnMtY2xpZW50Ijp7InJvbGVzIjpbInVtYV9wcm90ZWN0aW9uIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJjbGllbnRJZCI6InNlYW5zLWNsaWVudCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjE5Mi4xNjguOS4xIiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LXNlYW5zLWNsaWVudCIsImNsaWVudEFkZHJlc3MiOiIxOTIuMTY4LjkuMSJ9.BXA_5WhcNlO4Hv_grmNlKFhUfOa57m-1hSMyVrvyn58bhB7tZCoiLsL4BrVttdbKmzKVSjifMqr8mUDT21nu_pqSCgJ45WnjMobg8TX6Ysae0WaXI1gKH4Dm_EZXigdcpsV9EjXp7HFKA38-P1eOruU9OjXgY-X0dJW9yl6PRBRbp2mO_NBE88Igkt3nuDCBcbhiXN0bKYn0Fh4xbHIyeSIwuHt5dfZgdm93dLRtTc5DtzHb_oKEqJvbOS5dtP4XatykI92yYe-xDtbyuuCvPoowYNcP4wy09XYWsqOoYucFefMMPehto0Y0LHIjRQbB4gW9IQhOBtOk5HstEn5H4g",
  "expires_in": 60,
  "refresh_expires_in": 1800,
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1YTZkNzIxYS04MzJjLTRiMGQtOTkwZC1lZmE2ZTFhMjdlODIifQ.eyJleHAiOjE1OTM3NjEwNjQsImlhdCI6MTU5Mzc1OTI2NCwianRpIjoiM2UxZDhmYTEtYWJmYi00MjZlLTkzODgtYjc3OTRhZGM2MDJiIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJzdWIiOiJhYTBhZTc4OC1jYjEwLTQ0OTEtYTg2ZS1jOWJjZmUzOWRhMTQiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoic2VhbnMtY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6IjViNTY1OGY1LWYyOGYtNDI0Mi1iNTQ2LWI5Y2MwYzcwZDhhNiIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCJ9.VSa_fLlnUIyw03y0Wg1Qv_5LVIxEkhojsolHsneb28w",
  "token_type": "bearer",
  "not-before-policy": 0,
  "session_state": "5b5658f5-f28f-4242-b546-b9cc0c70d8a6",
  "scope": "profile email"
}
